IMAGE_REF = 'wasm-platform-registry.localhost:5001/gateway'

def gateway(resource_deps=[]):
    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' --build-context workspace=.' +
            ' --build-arg WORKSPACE_DEPS_IMAGE=$TILT_IMAGE_0' +
            ' -f components/gateway/Dockerfile' +
            ' -t $EXPECTED_REF' +
            ' components/gateway'
        ),
        deps = [
            'components/gateway/src',
            'components/gateway/Cargo.toml',
            'proto/gateway/v1/gateway.proto',
        ],
        image_deps = ['workspace-deps'],
    )

    k8s_resource(
        'gateway',
        labels = ['platform'],
        port_forwards = [3000],
        resource_deps = resource_deps,
    )
