// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gateway/v1/gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayRoutes_RequestFullRoutes_FullMethodName = "/gateway.v1.GatewayRoutes/RequestFullRoutes"
	GatewayRoutes_PushRouteUpdate_FullMethodName   = "/gateway.v1.GatewayRoutes/PushRouteUpdate"
)

// GatewayRoutesClient is the client API for GatewayRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayRoutesClient interface {
	// Gateway requests full route snapshot (on startup or desync)
	RequestFullRoutes(ctx context.Context, in *FullRoutesRequest, opts ...grpc.CallOption) (*FullRoutesResponse, error)
	// Bidirectional stream: operator pushes incremental route updates; gateway streams acks
	PushRouteUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteUpdateAck, RouteUpdateRequest], error)
}

type gatewayRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayRoutesClient(cc grpc.ClientConnInterface) GatewayRoutesClient {
	return &gatewayRoutesClient{cc}
}

func (c *gatewayRoutesClient) RequestFullRoutes(ctx context.Context, in *FullRoutesRequest, opts ...grpc.CallOption) (*FullRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullRoutesResponse)
	err := c.cc.Invoke(ctx, GatewayRoutes_RequestFullRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayRoutesClient) PushRouteUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteUpdateAck, RouteUpdateRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayRoutes_ServiceDesc.Streams[0], GatewayRoutes_PushRouteUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouteUpdateAck, RouteUpdateRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayRoutes_PushRouteUpdateClient = grpc.BidiStreamingClient[RouteUpdateAck, RouteUpdateRequest]

// GatewayRoutesServer is the server API for GatewayRoutes service.
// All implementations must embed UnimplementedGatewayRoutesServer
// for forward compatibility.
type GatewayRoutesServer interface {
	// Gateway requests full route snapshot (on startup or desync)
	RequestFullRoutes(context.Context, *FullRoutesRequest) (*FullRoutesResponse, error)
	// Bidirectional stream: operator pushes incremental route updates; gateway streams acks
	PushRouteUpdate(grpc.BidiStreamingServer[RouteUpdateAck, RouteUpdateRequest]) error
	mustEmbedUnimplementedGatewayRoutesServer()
}

// UnimplementedGatewayRoutesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayRoutesServer struct{}

func (UnimplementedGatewayRoutesServer) RequestFullRoutes(context.Context, *FullRoutesRequest) (*FullRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFullRoutes not implemented")
}
func (UnimplementedGatewayRoutesServer) PushRouteUpdate(grpc.BidiStreamingServer[RouteUpdateAck, RouteUpdateRequest]) error {
	return status.Error(codes.Unimplemented, "method PushRouteUpdate not implemented")
}
func (UnimplementedGatewayRoutesServer) mustEmbedUnimplementedGatewayRoutesServer() {}
func (UnimplementedGatewayRoutesServer) testEmbeddedByValue()                       {}

// UnsafeGatewayRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayRoutesServer will
// result in compilation errors.
type UnsafeGatewayRoutesServer interface {
	mustEmbedUnimplementedGatewayRoutesServer()
}

func RegisterGatewayRoutesServer(s grpc.ServiceRegistrar, srv GatewayRoutesServer) {
	// If the following call panics, it indicates UnimplementedGatewayRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayRoutes_ServiceDesc, srv)
}

func _GatewayRoutes_RequestFullRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayRoutesServer).RequestFullRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayRoutes_RequestFullRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayRoutesServer).RequestFullRoutes(ctx, req.(*FullRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayRoutes_PushRouteUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayRoutesServer).PushRouteUpdate(&grpc.GenericServerStream[RouteUpdateAck, RouteUpdateRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayRoutes_PushRouteUpdateServer = grpc.BidiStreamingServer[RouteUpdateAck, RouteUpdateRequest]

// GatewayRoutes_ServiceDesc is the grpc.ServiceDesc for GatewayRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayRoutes",
	HandlerType: (*GatewayRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestFullRoutes",
			Handler:    _GatewayRoutes_RequestFullRoutes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushRouteUpdate",
			Handler:       _GatewayRoutes_PushRouteUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/v1/gateway.proto",
}
