// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway/v1/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FullRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullRoutesRequest) Reset() {
	*x = FullRoutesRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullRoutesRequest) ProtoMessage() {}

func (x *FullRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullRoutesRequest.ProtoReflect.Descriptor instead.
func (*FullRoutesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *FullRoutesRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type FullRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteConfig         `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullRoutesResponse) Reset() {
	*x = FullRoutesResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullRoutesResponse) ProtoMessage() {}

func (x *FullRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullRoutesResponse.ProtoReflect.Descriptor instead.
func (*FullRoutesResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *FullRoutesResponse) GetRoutes() []*RouteConfig {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *FullRoutesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FullRoutesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FullRoutesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FullRoutesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteUpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Update          *RouteUpdateConfig     `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	TargetGatewayId string                 `protobuf:"bytes,2,opt,name=target_gateway_id,json=targetGatewayId,proto3" json:"target_gateway_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteUpdateRequest) Reset() {
	*x = RouteUpdateRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateRequest) ProtoMessage() {}

func (x *RouteUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateRequest.ProtoReflect.Descriptor instead.
func (*RouteUpdateRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RouteUpdateRequest) GetUpdate() *RouteUpdateConfig {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RouteUpdateRequest) GetTargetGatewayId() string {
	if x != nil {
		return x.TargetGatewayId
	}
	return ""
}

type RouteUpdateAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayId      string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	VersionApplied string                 `protobuf:"bytes,2,opt,name=version_applied,json=versionApplied,proto3" json:"version_applied,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteUpdateAck) Reset() {
	*x = RouteUpdateAck{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateAck) ProtoMessage() {}

func (x *RouteUpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateAck.ProtoReflect.Descriptor instead.
func (*RouteUpdateAck) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RouteUpdateAck) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *RouteUpdateAck) GetVersionApplied() string {
	if x != nil {
		return x.VersionApplied
	}
	return ""
}

func (x *RouteUpdateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteUpdateAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RouteUpdateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Updates       []*RouteUpdate         `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdateConfig) Reset() {
	*x = RouteUpdateConfig{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateConfig) ProtoMessage() {}

func (x *RouteUpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateConfig.ProtoReflect.Descriptor instead.
func (*RouteUpdateConfig) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RouteUpdateConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RouteUpdateConfig) GetUpdates() []*RouteUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *RouteUpdateConfig) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *RouteConfig           `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Delete        bool                   `protobuf:"varint,2,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *RouteUpdate) GetRoute() *RouteConfig {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *RouteUpdate) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type RouteConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	NatsSubject   string                 `protobuf:"bytes,3,opt,name=nats_subject,json=natsSubject,proto3" json:"nats_subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *RouteConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteConfig) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *RouteConfig) GetNatsSubject() string {
	if x != nil {
		return x.NatsSubject
	}
	return ""
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"2\n" +
	"\x11FullRoutesRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\"\xb1\x01\n" +
	"\x12FullRoutesResponse\x12/\n" +
	"\x06routes\x18\x01 \x03(\v2\x17.gateway.v1.RouteConfigR\x06routes\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"w\n" +
	"\x12RouteUpdateRequest\x125\n" +
	"\x06update\x18\x01 \x01(\v2\x1d.gateway.v1.RouteUpdateConfigR\x06update\x12*\n" +
	"\x11target_gateway_id\x18\x02 \x01(\tR\x0ftargetGatewayId\"\x8c\x01\n" +
	"\x0eRouteUpdateAck\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12'\n" +
	"\x0fversion_applied\x18\x02 \x01(\tR\x0eversionApplied\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"~\n" +
	"\x11RouteUpdateConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x121\n" +
	"\aupdates\x18\x02 \x03(\v2\x17.gateway.v1.RouteUpdateR\aupdates\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"T\n" +
	"\vRouteUpdate\x12-\n" +
	"\x05route\x18\x01 \x01(\v2\x17.gateway.v1.RouteConfigR\x05route\x12\x16\n" +
	"\x06delete\x18\x02 \x01(\bR\x06delete\"^\n" +
	"\vRouteConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods\x12!\n" +
	"\fnats_subject\x18\x03 \x01(\tR\vnatsSubject2\xb6\x01\n" +
	"\rGatewayRoutes\x12R\n" +
	"\x11RequestFullRoutes\x12\x1d.gateway.v1.FullRoutesRequest\x1a\x1e.gateway.v1.FullRoutesResponse\x12Q\n" +
	"\x0fPushRouteUpdate\x12\x1a.gateway.v1.RouteUpdateAck\x1a\x1e.gateway.v1.RouteUpdateRequest(\x010\x01BLZJgithub.com/benjamin-wright/wasm-platform/wp-operator/internal/grpc/gatewayb\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*FullRoutesRequest)(nil),  // 0: gateway.v1.FullRoutesRequest
	(*FullRoutesResponse)(nil), // 1: gateway.v1.FullRoutesResponse
	(*RouteUpdateRequest)(nil), // 2: gateway.v1.RouteUpdateRequest
	(*RouteUpdateAck)(nil),     // 3: gateway.v1.RouteUpdateAck
	(*RouteUpdateConfig)(nil),  // 4: gateway.v1.RouteUpdateConfig
	(*RouteUpdate)(nil),        // 5: gateway.v1.RouteUpdate
	(*RouteConfig)(nil),        // 6: gateway.v1.RouteConfig
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	6, // 0: gateway.v1.FullRoutesResponse.routes:type_name -> gateway.v1.RouteConfig
	4, // 1: gateway.v1.RouteUpdateRequest.update:type_name -> gateway.v1.RouteUpdateConfig
	5, // 2: gateway.v1.RouteUpdateConfig.updates:type_name -> gateway.v1.RouteUpdate
	6, // 3: gateway.v1.RouteUpdate.route:type_name -> gateway.v1.RouteConfig
	0, // 4: gateway.v1.GatewayRoutes.RequestFullRoutes:input_type -> gateway.v1.FullRoutesRequest
	3, // 5: gateway.v1.GatewayRoutes.PushRouteUpdate:input_type -> gateway.v1.RouteUpdateAck
	1, // 6: gateway.v1.GatewayRoutes.RequestFullRoutes:output_type -> gateway.v1.FullRoutesResponse
	2, // 7: gateway.v1.GatewayRoutes.PushRouteUpdate:output_type -> gateway.v1.RouteUpdateRequest
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
