def sql_hello(namespace, resource_deps=[]):
    k8s_kind('Application',
             image_json_path = '{.spec.functions[*].module}',
             pod_readiness = 'ignore')

    custom_build(
        'sql-hello-setup',
        command = (
            'cargo build --manifest-path examples/sql-hello/fns/setup/Cargo.toml' +
            ' --target wasm32-wasip2 --release --target-dir target &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/sql_hello_setup.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/sql-hello/fns/setup/src',
            'examples/sql-hello/fns/setup/Cargo.toml',
            'examples/sql-hello/Cargo.toml',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    custom_build(
        'sql-hello-query',
        command = (
            'cargo build --manifest-path examples/sql-hello/fns/query/Cargo.toml' +
            ' --target wasm32-wasip2 --release --target-dir target &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/sql_hello_query.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/sql-hello/fns/query/src',
            'examples/sql-hello/fns/query/Cargo.toml',
            'examples/sql-hello/Cargo.toml',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    custom_build(
        'sql-hello-insert-test',
        command = (
            'cargo build --manifest-path examples/sql-hello/fns/insert-test/Cargo.toml' +
            ' --target wasm32-wasip2 --release --target-dir target &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/sql_hello_insert_test.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/sql-hello/fns/insert-test/src',
            'examples/sql-hello/fns/insert-test/Cargo.toml',
            'examples/sql-hello/Cargo.toml',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    k8s_yaml('examples/sql-hello/k8s/application.yaml')

    k8s_resource(
        'sql-hello',
        resource_deps = ['module-cache', 'wp-operator'] + resource_deps,
        labels = ['example'],
    )
