def demo_app(namespace, resource_deps=[]):
    custom_build(
        'demo-app-http',
        command = (
            'cargo build --manifest-path examples/demo-app/http-handler/Cargo.toml' +
            ' --target wasm32-wasip2 --release --locked &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/http_handler.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/demo-app/http-handler/src',
            'examples/demo-app/http-handler/Cargo.toml',
            'Cargo.toml',
            'Cargo.lock',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    custom_build(
        'demo-app-messages',
        command = (
            'cargo build --manifest-path examples/demo-app/message-handler/Cargo.toml' +
            ' --target wasm32-wasip2 --release --locked &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/message_handler.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/demo-app/message-handler/src',
            'examples/demo-app/message-handler/Cargo.toml',
            'Cargo.toml',
            'Cargo.lock',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    k8s_yaml('examples/demo-app/k8s/application.yaml')

    k8s_resource(
        'demo-app',
        resource_deps = ['module-cache', 'wp-operator'] + resource_deps,
        labels = ['example'],
    )
