apiVersion: wasm-platform.io/v1alpha1
kind: Application
metadata:
  name: counter-app
  namespace: examples
spec:
  keyValue: counter-app
  functions:
    - name: http-handler
      module: counter-app-http
      trigger:
        http:
          path: /counter
          methods:
            - GET
