def counter_app(namespace, resource_deps=[]):
    custom_build(
        'counter-app-http',
        command = (
            'cargo build --manifest-path examples/counter-app/Cargo.toml' +
            ' --target wasm32-wasip2 --release --target-dir target &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/counter_app.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/counter-app/lib.rs',
            'examples/counter-app/Cargo.toml',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    k8s_yaml('examples/counter-app/application.yaml')

    k8s_resource(
        'counter-app',
        resource_deps = ['module-cache', 'wp-operator'] + resource_deps,
        labels = ['example'],
    )
