apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: RedisDatabase
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.labels" . | nindent 4 }}
spec:
  storageSize: {{ .Values.redis.storageSize }}
---
apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: RedisCredential
metadata:
  name: {{ .Release.Name }}-redis-wp-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.labels" . | nindent 4 }}
spec:
  databaseRef: {{ .Release.Name }}-redis
  username: {{ .Values.redis.wpOperator.username }}
  secretName: {{ .Values.redis.wpOperator.secretName }}
  aclCategories:
    - all
