image:
  repository: wasm-platform-registry.localhost:5001/execution-host
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

replicaCount: 1

nats:
  secretName: execution-host-nats-credentials

configSync:
  serverAddr: "http://wp-operator-grpc:50051"

moduleCache:
  addr: "http://module-cache:80"

logLevel: info
