def message_counter(namespace, resource_deps=[]):
    k8s_kind('Application',
             image_json_path = '{.spec.module}',
             pod_readiness = 'ignore')

    custom_build(
        'message-counter',
        command = (
            'cargo build --manifest-path examples/message-counter/Cargo.toml' +
            ' --target wasm32-wasip2 --release &&' +
            ' oras push $EXPECTED_REF' +
            ' target/wasm32-wasip2/release/message_counter.wasm' +
            ' --artifact-type application/vnd.wasm.content.layer.v1+wasm' +
            ' --plain-http'
        ),
        deps = [
            'examples/message-counter/src',
            'framework/runtime.wit',
        ],
        skips_local_docker = True,
    )

    k8s_yaml('examples/message-counter/k8s/application.yaml')

    k8s_resource(
        'message-counter',
        resource_deps = ['module-cache', 'wp-operator'] + resource_deps,
        labels = ['example'],
    )
