// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: configsync/v1/configsync.proto

package configsync

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSync_RequestFullConfig_FullMethodName     = "/configsync.v1.ConfigSync/RequestFullConfig"
	ConfigSync_PushIncrementalUpdate_FullMethodName = "/configsync.v1.ConfigSync/PushIncrementalUpdate"
)

// ConfigSyncClient is the client API for ConfigSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigSyncClient interface {
	// Host requests full configuration snapshot (on startup or desync)
	RequestFullConfig(ctx context.Context, in *FullConfigRequest, opts ...grpc.CallOption) (*FullConfigResponse, error)
	// Bidirectional stream: operator pushes incremental updates; host streams acks
	PushIncrementalUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IncrementalUpdateAck, IncrementalUpdateRequest], error)
}

type configSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncClient(cc grpc.ClientConnInterface) ConfigSyncClient {
	return &configSyncClient{cc}
}

func (c *configSyncClient) RequestFullConfig(ctx context.Context, in *FullConfigRequest, opts ...grpc.CallOption) (*FullConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullConfigResponse)
	err := c.cc.Invoke(ctx, ConfigSync_RequestFullConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSyncClient) PushIncrementalUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IncrementalUpdateAck, IncrementalUpdateRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSync_ServiceDesc.Streams[0], ConfigSync_PushIncrementalUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IncrementalUpdateAck, IncrementalUpdateRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_PushIncrementalUpdateClient = grpc.BidiStreamingClient[IncrementalUpdateAck, IncrementalUpdateRequest]

// ConfigSyncServer is the server API for ConfigSync service.
// All implementations must embed UnimplementedConfigSyncServer
// for forward compatibility.
type ConfigSyncServer interface {
	// Host requests full configuration snapshot (on startup or desync)
	RequestFullConfig(context.Context, *FullConfigRequest) (*FullConfigResponse, error)
	// Bidirectional stream: operator pushes incremental updates; host streams acks
	PushIncrementalUpdate(grpc.BidiStreamingServer[IncrementalUpdateAck, IncrementalUpdateRequest]) error
	mustEmbedUnimplementedConfigSyncServer()
}

// UnimplementedConfigSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServer struct{}

func (UnimplementedConfigSyncServer) RequestFullConfig(context.Context, *FullConfigRequest) (*FullConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFullConfig not implemented")
}
func (UnimplementedConfigSyncServer) PushIncrementalUpdate(grpc.BidiStreamingServer[IncrementalUpdateAck, IncrementalUpdateRequest]) error {
	return status.Error(codes.Unimplemented, "method PushIncrementalUpdate not implemented")
}
func (UnimplementedConfigSyncServer) mustEmbedUnimplementedConfigSyncServer() {}
func (UnimplementedConfigSyncServer) testEmbeddedByValue()                    {}

// UnsafeConfigSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServer will
// result in compilation errors.
type UnsafeConfigSyncServer interface {
	mustEmbedUnimplementedConfigSyncServer()
}

func RegisterConfigSyncServer(s grpc.ServiceRegistrar, srv ConfigSyncServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSync_ServiceDesc, srv)
}

func _ConfigSync_RequestFullConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSyncServer).RequestFullConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSync_RequestFullConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSyncServer).RequestFullConfig(ctx, req.(*FullConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSync_PushIncrementalUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigSyncServer).PushIncrementalUpdate(&grpc.GenericServerStream[IncrementalUpdateAck, IncrementalUpdateRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_PushIncrementalUpdateServer = grpc.BidiStreamingServer[IncrementalUpdateAck, IncrementalUpdateRequest]

// ConfigSync_ServiceDesc is the grpc.ServiceDesc for ConfigSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configsync.v1.ConfigSync",
	HandlerType: (*ConfigSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestFullConfig",
			Handler:    _ConfigSync_RequestFullConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushIncrementalUpdate",
			Handler:       _ConfigSync_PushIncrementalUpdate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "configsync/v1/configsync.proto",
}
