// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: configsync/v1/configsync.proto

package configsync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorldType int32

const (
	WorldType_WORLD_TYPE_MESSAGE WorldType = 0
	WorldType_WORLD_TYPE_HTTP    WorldType = 1
)

// Enum value maps for WorldType.
var (
	WorldType_name = map[int32]string{
		0: "WORLD_TYPE_MESSAGE",
		1: "WORLD_TYPE_HTTP",
	}
	WorldType_value = map[string]int32{
		"WORLD_TYPE_MESSAGE": 0,
		"WORLD_TYPE_HTTP":    1,
	}
)

func (x WorldType) Enum() *WorldType {
	p := new(WorldType)
	*p = x
	return p
}

func (x WorldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorldType) Descriptor() protoreflect.EnumDescriptor {
	return file_configsync_v1_configsync_proto_enumTypes[0].Descriptor()
}

func (WorldType) Type() protoreflect.EnumType {
	return &file_configsync_v1_configsync_proto_enumTypes[0]
}

func (x WorldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorldType.Descriptor instead.
func (WorldType) EnumDescriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{0}
}

type FullConfigRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HostId           string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	LastAckTimestamp *int64                 `protobuf:"varint,2,opt,name=last_ack_timestamp,json=lastAckTimestamp,proto3,oneof" json:"last_ack_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FullConfigRequest) Reset() {
	*x = FullConfigRequest{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullConfigRequest) ProtoMessage() {}

func (x *FullConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullConfigRequest.ProtoReflect.Descriptor instead.
func (*FullConfigRequest) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{0}
}

func (x *FullConfigRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *FullConfigRequest) GetLastAckTimestamp() int64 {
	if x != nil && x.LastAckTimestamp != nil {
		return *x.LastAckTimestamp
	}
	return 0
}

type FullConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *FullConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullConfigResponse) Reset() {
	*x = FullConfigResponse{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullConfigResponse) ProtoMessage() {}

func (x *FullConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullConfigResponse.ProtoReflect.Descriptor instead.
func (*FullConfigResponse) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{1}
}

func (x *FullConfigResponse) GetConfig() *FullConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FullConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FullConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FullConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Applications  []*ApplicationConfig   `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullConfig) Reset() {
	*x = FullConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullConfig) ProtoMessage() {}

func (x *FullConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullConfig.ProtoReflect.Descriptor instead.
func (*FullConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{2}
}

func (x *FullConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FullConfig) GetApplications() []*ApplicationConfig {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *FullConfig) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IncrementalUpdateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncrementalConfig *IncrementalConfig     `protobuf:"bytes,1,opt,name=incremental_config,json=incrementalConfig,proto3" json:"incremental_config,omitempty"`
	TargetHostId      string                 `protobuf:"bytes,2,opt,name=target_host_id,json=targetHostId,proto3" json:"target_host_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IncrementalUpdateRequest) Reset() {
	*x = IncrementalUpdateRequest{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalUpdateRequest) ProtoMessage() {}

func (x *IncrementalUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalUpdateRequest.ProtoReflect.Descriptor instead.
func (*IncrementalUpdateRequest) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{3}
}

func (x *IncrementalUpdateRequest) GetIncrementalConfig() *IncrementalConfig {
	if x != nil {
		return x.IncrementalConfig
	}
	return nil
}

func (x *IncrementalUpdateRequest) GetTargetHostId() string {
	if x != nil {
		return x.TargetHostId
	}
	return ""
}

type IncrementalUpdateAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	VersionApplied string                 `protobuf:"bytes,2,opt,name=version_applied,json=versionApplied,proto3" json:"version_applied,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncrementalUpdateAck) Reset() {
	*x = IncrementalUpdateAck{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalUpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalUpdateAck) ProtoMessage() {}

func (x *IncrementalUpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalUpdateAck.ProtoReflect.Descriptor instead.
func (*IncrementalUpdateAck) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementalUpdateAck) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *IncrementalUpdateAck) GetVersionApplied() string {
	if x != nil {
		return x.VersionApplied
	}
	return ""
}

func (x *IncrementalUpdateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IncrementalUpdateAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IncrementalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Updates       []*AppUpdate           `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementalConfig) Reset() {
	*x = IncrementalConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalConfig) ProtoMessage() {}

func (x *IncrementalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalConfig.ProtoReflect.Descriptor instead.
func (*IncrementalConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{5}
}

func (x *IncrementalConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IncrementalConfig) GetUpdates() []*AppUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *IncrementalConfig) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AppUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppConfig     *ApplicationConfig     `protobuf:"bytes,1,opt,name=app_config,json=appConfig,proto3" json:"app_config,omitempty"`
	Delete        bool                   `protobuf:"varint,2,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUpdate) Reset() {
	*x = AppUpdate{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpdate) ProtoMessage() {}

func (x *AppUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpdate.ProtoReflect.Descriptor instead.
func (*AppUpdate) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{6}
}

func (x *AppUpdate) GetAppConfig() *ApplicationConfig {
	if x != nil {
		return x.AppConfig
	}
	return nil
}

func (x *AppUpdate) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type ApplicationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ModuleRef     string                 `protobuf:"bytes,3,opt,name=module_ref,json=moduleRef,proto3" json:"module_ref,omitempty"`
	Topic         string                 `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sql           *SqlConfig             `protobuf:"bytes,6,opt,name=sql,proto3,oneof" json:"sql,omitempty"`
	KeyValue      *KeyValueConfig        `protobuf:"bytes,7,opt,name=key_value,json=keyValue,proto3,oneof" json:"key_value,omitempty"`
	WorldType     WorldType              `protobuf:"varint,8,opt,name=world_type,json=worldType,proto3,enum=configsync.v1.WorldType" json:"world_type,omitempty"`
	Http          *HttpConfig            `protobuf:"bytes,9,opt,name=http,proto3,oneof" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationConfig) Reset() {
	*x = ApplicationConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfig) ProtoMessage() {}

func (x *ApplicationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfig.ProtoReflect.Descriptor instead.
func (*ApplicationConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{7}
}

func (x *ApplicationConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplicationConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ApplicationConfig) GetModuleRef() string {
	if x != nil {
		return x.ModuleRef
	}
	return ""
}

func (x *ApplicationConfig) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ApplicationConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ApplicationConfig) GetSql() *SqlConfig {
	if x != nil {
		return x.Sql
	}
	return nil
}

func (x *ApplicationConfig) GetKeyValue() *KeyValueConfig {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

func (x *ApplicationConfig) GetWorldType() WorldType {
	if x != nil {
		return x.WorldType
	}
	return WorldType_WORLD_TYPE_MESSAGE
}

func (x *ApplicationConfig) GetHttp() *HttpConfig {
	if x != nil {
		return x.Http
	}
	return nil
}

type SqlConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseName  string                 `protobuf:"bytes,1,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	ConnectionUrl string                 `protobuf:"bytes,2,opt,name=connection_url,json=connectionUrl,proto3" json:"connection_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlConfig) Reset() {
	*x = SqlConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlConfig) ProtoMessage() {}

func (x *SqlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlConfig.ProtoReflect.Descriptor instead.
func (*SqlConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{8}
}

func (x *SqlConfig) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *SqlConfig) GetConnectionUrl() string {
	if x != nil {
		return x.ConnectionUrl
	}
	return ""
}

type KeyValueConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	ConnectionUrl string                 `protobuf:"bytes,2,opt,name=connection_url,json=connectionUrl,proto3" json:"connection_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueConfig) Reset() {
	*x = KeyValueConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueConfig) ProtoMessage() {}

func (x *KeyValueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueConfig.ProtoReflect.Descriptor instead.
func (*KeyValueConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{9}
}

func (x *KeyValueConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *KeyValueConfig) GetConnectionUrl() string {
	if x != nil {
		return x.ConnectionUrl
	}
	return ""
}

type HttpConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Methods       []string               `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpConfig) Reset() {
	*x = HttpConfig{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpConfig) ProtoMessage() {}

func (x *HttpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpConfig.ProtoReflect.Descriptor instead.
func (*HttpConfig) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{10}
}

func (x *HttpConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpConfig) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

var File_configsync_v1_configsync_proto protoreflect.FileDescriptor

const file_configsync_v1_configsync_proto_rawDesc = "" +
	"\n" +
	"\x1econfigsync/v1/configsync.proto\x12\rconfigsync.v1\"v\n" +
	"\x11FullConfigRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x121\n" +
	"\x12last_ack_timestamp\x18\x02 \x01(\x03H\x00R\x10lastAckTimestamp\x88\x01\x01B\x15\n" +
	"\x13_last_ack_timestamp\"{\n" +
	"\x12FullConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.configsync.v1.FullConfigR\x06config\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8a\x01\n" +
	"\n" +
	"FullConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12D\n" +
	"\fapplications\x18\x02 \x03(\v2 .configsync.v1.ApplicationConfigR\fapplications\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x91\x01\n" +
	"\x18IncrementalUpdateRequest\x12O\n" +
	"\x12incremental_config\x18\x01 \x01(\v2 .configsync.v1.IncrementalConfigR\x11incrementalConfig\x12$\n" +
	"\x0etarget_host_id\x18\x02 \x01(\tR\ftargetHostId\"\x8c\x01\n" +
	"\x14IncrementalUpdateAck\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12'\n" +
	"\x0fversion_applied\x18\x02 \x01(\tR\x0eversionApplied\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x7f\n" +
	"\x11IncrementalConfig\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x122\n" +
	"\aupdates\x18\x02 \x03(\v2\x18.configsync.v1.AppUpdateR\aupdates\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"d\n" +
	"\tAppUpdate\x12?\n" +
	"\n" +
	"app_config\x18\x01 \x01(\v2 .configsync.v1.ApplicationConfigR\tappConfig\x12\x16\n" +
	"\x06delete\x18\x02 \x01(\bR\x06delete\"\xed\x03\n" +
	"\x11ApplicationConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"module_ref\x18\x03 \x01(\tR\tmoduleRef\x12\x14\n" +
	"\x05topic\x18\x04 \x01(\tR\x05topic\x12;\n" +
	"\x03env\x18\x05 \x03(\v2).configsync.v1.ApplicationConfig.EnvEntryR\x03env\x12/\n" +
	"\x03sql\x18\x06 \x01(\v2\x18.configsync.v1.SqlConfigH\x00R\x03sql\x88\x01\x01\x12?\n" +
	"\tkey_value\x18\a \x01(\v2\x1d.configsync.v1.KeyValueConfigH\x01R\bkeyValue\x88\x01\x01\x127\n" +
	"\n" +
	"world_type\x18\b \x01(\x0e2\x18.configsync.v1.WorldTypeR\tworldType\x122\n" +
	"\x04http\x18\t \x01(\v2\x19.configsync.v1.HttpConfigH\x02R\x04http\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_sqlB\f\n" +
	"\n" +
	"_key_valueB\a\n" +
	"\x05_http\"W\n" +
	"\tSqlConfig\x12#\n" +
	"\rdatabase_name\x18\x01 \x01(\tR\fdatabaseName\x12%\n" +
	"\x0econnection_url\x18\x02 \x01(\tR\rconnectionUrl\"O\n" +
	"\x0eKeyValueConfig\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12%\n" +
	"\x0econnection_url\x18\x02 \x01(\tR\rconnectionUrl\":\n" +
	"\n" +
	"HttpConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amethods\x18\x02 \x03(\tR\amethods*8\n" +
	"\tWorldType\x12\x16\n" +
	"\x12WORLD_TYPE_MESSAGE\x10\x00\x12\x13\n" +
	"\x0fWORLD_TYPE_HTTP\x10\x012\xd1\x01\n" +
	"\n" +
	"ConfigSync\x12X\n" +
	"\x11RequestFullConfig\x12 .configsync.v1.FullConfigRequest\x1a!.configsync.v1.FullConfigResponse\x12i\n" +
	"\x15PushIncrementalUpdate\x12#.configsync.v1.IncrementalUpdateAck\x1a'.configsync.v1.IncrementalUpdateRequest(\x010\x01BOZMgithub.com/benjamin-wright/wasm-platform/wp-operator/internal/grpc/configsyncb\x06proto3"

var (
	file_configsync_v1_configsync_proto_rawDescOnce sync.Once
	file_configsync_v1_configsync_proto_rawDescData []byte
)

func file_configsync_v1_configsync_proto_rawDescGZIP() []byte {
	file_configsync_v1_configsync_proto_rawDescOnce.Do(func() {
		file_configsync_v1_configsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configsync_v1_configsync_proto_rawDesc), len(file_configsync_v1_configsync_proto_rawDesc)))
	})
	return file_configsync_v1_configsync_proto_rawDescData
}

var file_configsync_v1_configsync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configsync_v1_configsync_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_configsync_v1_configsync_proto_goTypes = []any{
	(WorldType)(0),                   // 0: configsync.v1.WorldType
	(*FullConfigRequest)(nil),        // 1: configsync.v1.FullConfigRequest
	(*FullConfigResponse)(nil),       // 2: configsync.v1.FullConfigResponse
	(*FullConfig)(nil),               // 3: configsync.v1.FullConfig
	(*IncrementalUpdateRequest)(nil), // 4: configsync.v1.IncrementalUpdateRequest
	(*IncrementalUpdateAck)(nil),     // 5: configsync.v1.IncrementalUpdateAck
	(*IncrementalConfig)(nil),        // 6: configsync.v1.IncrementalConfig
	(*AppUpdate)(nil),                // 7: configsync.v1.AppUpdate
	(*ApplicationConfig)(nil),        // 8: configsync.v1.ApplicationConfig
	(*SqlConfig)(nil),                // 9: configsync.v1.SqlConfig
	(*KeyValueConfig)(nil),           // 10: configsync.v1.KeyValueConfig
	(*HttpConfig)(nil),               // 11: configsync.v1.HttpConfig
	nil,                              // 12: configsync.v1.ApplicationConfig.EnvEntry
}
var file_configsync_v1_configsync_proto_depIdxs = []int32{
	3,  // 0: configsync.v1.FullConfigResponse.config:type_name -> configsync.v1.FullConfig
	8,  // 1: configsync.v1.FullConfig.applications:type_name -> configsync.v1.ApplicationConfig
	6,  // 2: configsync.v1.IncrementalUpdateRequest.incremental_config:type_name -> configsync.v1.IncrementalConfig
	7,  // 3: configsync.v1.IncrementalConfig.updates:type_name -> configsync.v1.AppUpdate
	8,  // 4: configsync.v1.AppUpdate.app_config:type_name -> configsync.v1.ApplicationConfig
	12, // 5: configsync.v1.ApplicationConfig.env:type_name -> configsync.v1.ApplicationConfig.EnvEntry
	9,  // 6: configsync.v1.ApplicationConfig.sql:type_name -> configsync.v1.SqlConfig
	10, // 7: configsync.v1.ApplicationConfig.key_value:type_name -> configsync.v1.KeyValueConfig
	0,  // 8: configsync.v1.ApplicationConfig.world_type:type_name -> configsync.v1.WorldType
	11, // 9: configsync.v1.ApplicationConfig.http:type_name -> configsync.v1.HttpConfig
	1,  // 10: configsync.v1.ConfigSync.RequestFullConfig:input_type -> configsync.v1.FullConfigRequest
	5,  // 11: configsync.v1.ConfigSync.PushIncrementalUpdate:input_type -> configsync.v1.IncrementalUpdateAck
	2,  // 12: configsync.v1.ConfigSync.RequestFullConfig:output_type -> configsync.v1.FullConfigResponse
	4,  // 13: configsync.v1.ConfigSync.PushIncrementalUpdate:output_type -> configsync.v1.IncrementalUpdateRequest
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_configsync_v1_configsync_proto_init() }
func file_configsync_v1_configsync_proto_init() {
	if File_configsync_v1_configsync_proto != nil {
		return
	}
	file_configsync_v1_configsync_proto_msgTypes[0].OneofWrappers = []any{}
	file_configsync_v1_configsync_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configsync_v1_configsync_proto_rawDesc), len(file_configsync_v1_configsync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configsync_v1_configsync_proto_goTypes,
		DependencyIndexes: file_configsync_v1_configsync_proto_depIdxs,
		EnumInfos:         file_configsync_v1_configsync_proto_enumTypes,
		MessageInfos:      file_configsync_v1_configsync_proto_msgTypes,
	}.Build()
	File_configsync_v1_configsync_proto = out.File
	file_configsync_v1_configsync_proto_goTypes = nil
	file_configsync_v1_configsync_proto_depIdxs = nil
}
