use anyhow::Result;
use axum::{
    Router,
    extract::State,
    http::StatusCode,
    routing::{get, post},
};
use std::sync::Arc;
use wasmtime::{
    Engine,
    Store,
    component::{Component, Linker, ResourceTable, bindgen},
};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

// Generate typed bindings for the `application` world defined in runtime.wit.
// This gives us strongly-typed `call_on_request` / `call_on_schedule` /
// `call_on_message` methods and will also generate `add_to_linker` helpers
// for the `sql` and `kv` imports once we implement those host-side traits.
bindgen!({
    world: "application",
    path: "../../framework/runtime.wit",
});

// ── Host state ────────────────────────────────────────────────────────────────
// One instance per request/call.  Adding kv or sql support later is a one-liner
// per field; the WasiView impl below will not need to change.

struct HostState {
    wasi: WasiCtx,
    table: ResourceTable,
    // kv:  KvState,   // TODO: add when wiring up the kv host implementation
    // sql: SqlState,  // TODO: add when wiring up the sql host implementation
}

impl WasiView for HostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView { ctx: &mut self.wasi, table: &mut self.table }
    }
}

// ── Shared (process-wide) state ───────────────────────────────────────────────
// The Engine is expensive to create and is safe to share across threads.
// The Component is the pre-compiled wasm binary, also shareable.

struct RuntimeState {
    engine: Engine,
    component: Component,
}

// ── Entry point ───────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let mut config = wasmtime::Config::new();
    config.wasm_component_model(true);
    let engine = Engine::new(&config)?;

    // Module path is configured via WASM_MODULE_PATH. Defaults to the local
    // build output so `make run` works without any extra configuration.
    let wasm_path = std::env::var("WASM_MODULE_PATH").unwrap_or_else(|_| {
        concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../target/wasm32-wasip2/release/hello_world.wasm"
        )
        .to_string()
    });
    // .cwasm files are AOT-compiled artifacts produced by the precompile
    // binary; .wasm files are compiled at load time (used in local dev).
    let component = if wasm_path.ends_with(".cwasm") {
        // Safety: the file was produced by the precompile binary using the
        // same Engine configuration and Wasmtime version as this process.
        unsafe { Component::deserialize_file(&engine, &wasm_path)? }
    } else {
        Component::from_file(&engine, &wasm_path)?
    };

    let state = Arc::new(RuntimeState { engine, component });

    tracing::info!("execution-host starting");

    let app = Router::new()
        .route("/execute", post(execute_handler))
        .route("/healthz", get(healthz_handler))
        .with_state(state);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await?;
    axum::serve(listener, app).await?;
    Ok(())
}

// ── Handlers ──────────────────────────────────────────────────────────────────

async fn execute_handler(
    State(state): State<Arc<RuntimeState>>,
    body: axum::body::Bytes,
) -> (StatusCode, String) {
    tracing::info!("execute_handler called");

    // WASM execution is CPU-bound; run it on the blocking thread pool so the
    // async runtime stays responsive.
    let result = tokio::task::spawn_blocking(move || {
        invoke_on_request(&state, "POST", "/execute", &body)
    })
    .await;

    match result {
        Ok(Ok(response_body)) => {
            let text = String::from_utf8_lossy(&response_body).into_owned();
            (StatusCode::OK, text)
        }
        Ok(Err(err)) => {
            tracing::error!("invoke_on_request failed: {err:#}");
            (StatusCode::INTERNAL_SERVER_ERROR, format!("error: {err:#}"))
        }
        Err(join_err) => {
            tracing::error!("spawn_blocking panicked: {join_err}");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".to_string())
        }
    }
}

async fn healthz_handler() -> &'static str {
    tracing::info!("healthz_handler called");
    "OK"
}

// ── WASM invocation ───────────────────────────────────────────────────────────

fn invoke_on_request(state: &RuntimeState, method: &str, path: &str, body: &[u8]) -> Result<Vec<u8>> {
    let mut linker: Linker<HostState> = Linker::new(&state.engine);

    // Add WASI host functions.  When kv/sql are ready, call their equivalent
    // `add_to_linker` generated by bindgen! (or a hand-written one) here.
    wasmtime_wasi::p2::add_to_linker_sync(&mut linker)?;

    let host_state = HostState {
        wasi: WasiCtxBuilder::new().inherit_stderr().build(),
        table: ResourceTable::new(),
    };
    let mut store = Store::new(&state.engine, host_state);

    let app = Application::instantiate(&mut store, &state.component, &linker)?;

    let result = app.call_on_request(&mut store, method, path, body)?;

    result.map_err(|msg| anyhow::anyhow!("component returned errory: {msg}"))
}
