apiVersion: v1
kind: ServiceAccount
metadata:
  name: wp-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.wp-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wp-operator
  labels:
    {{- include "wasm-platform.wp-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["wasm-platform.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["wasm-platform.io"]
    resources: ["applications/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["wasm-platform.io"]
    resources: ["applications/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["db-operator.benjamin-wright.github.com"]
    resources: ["postgrescredentials"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["db-operator.benjamin-wright.github.com"]
    resources: ["postgresdatabases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["db-operator.benjamin-wright.github.com"]
    resources: ["postgresmigrationsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-wp-operator
  labels:
    {{- include "wasm-platform.wp-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-wp-operator
subjects:
  - kind: ServiceAccount
    name: wp-operator
    namespace: {{ .Release.Namespace }}
