apiVersion: v1
kind: Service
metadata:
  name: wp-operator-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.wp-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wp-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: {{ .Values.wpOperator.grpc.port }}
      targetPort: grpc
      protocol: TCP
