apiVersion: wasm-platform.io/v1alpha1
kind: Application
metadata:
  name: message-counter
  namespace: wasm-platform
spec:
  module: message-counter
  topic: hello-world.events
  keyValue: hello-world
