apiVersion: wasm-platform.io/v1alpha1
kind: Application
metadata:
  name: message-counter
  namespace: examples
spec:
  keyValue: hello-world
  functions:
    - name: handler
      module: message-counter
      trigger:
        topic: hello-world.events
