IMAGE_REF = 'wasm-platform-registry.localhost:5001/wp-operator'

# Release name used by helm() in the root Tiltfile.
# The ClusterRole and ClusterRoleBinding are named <release>-wp-operator.
RELEASE_NAME = 'wasm-platform'

def wp_operator(namespace='wasm-platform'):
    k8s_kind('Application',
             image_json_path = ['{.spec.functions[*].module}', '{.spec[?(@.migrations)].migrations.artifact}'],
             pod_readiness = 'ignore')

    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' -t $EXPECTED_REF' +
            ' components/wp-operator'
        ),
        deps = [
            'components/wp-operator/cmd',
            'components/wp-operator/api',
            'components/wp-operator/internal',
            'components/wp-operator/go.mod',
            'components/wp-operator/go.sum',
        ],
    )

    k8s_resource(
        'wp-operator',
        labels = ['platform'],
        port_forwards = ['50051:50051'],
        objects = [
            'wp-operator:ServiceAccount:{}'.format(namespace),
            '{}-wp-operator:ClusterRole'.format(RELEASE_NAME),
            '{}-wp-operator:ClusterRoleBinding'.format(RELEASE_NAME),
        ],
    )

    k8s_resource(
        new_name = 'wp-webhook',
        objects = [
            'wasm-platform-selfsigned:ClusterIssuer',
            'wp-operator-webhook-tls:Certificate:{}'.format(namespace),
            'wasm-platform-application-validator:ValidatingWebhookConfiguration',
        ],
        labels = ['platform'],
        resource_deps = ['cert-manager-ready'],
    )

    local_resource(
        'wp: unit-tests',
        cmd = 'cd components/wp-operator && go test ./...',
        deps = [
            'components/wp-operator/cmd',
            'components/wp-operator/api',
            'components/wp-operator/internal',
        ],
        labels = ['tests'],
        auto_init=False,
        trigger_mode = TRIGGER_MODE_MANUAL,
    )

    local_resource(
        'wp: integration-tests',
        cmd = 'cd components/wp-operator && go test -tags integration -v ./internal/integration/...',
        deps = [
            'components/wp-operator/internal/integration',
        ],
        resource_deps = ['wp-operator'],
        labels = ['tests'],
        auto_init=False,
        trigger_mode = TRIGGER_MODE_MANUAL,
    )
