apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: PostgresDatabase
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wp-databases.labels" . | nindent 4 }}
spec:
  postgresVersion: {{ .Values.postgres.version | quote }}
  storageSize: {{ .Values.postgres.storageSize }}
