load('ext://helm_resource', 'helm_resource')

IMAGE_REF = 'wasm-platform-registry.localhost:5001/execution-host'

def execution_host(namespace, resource_deps=[]):
    local_resource(
        'hello-wasm',
        cmd = 'cargo build --manifest-path examples/hello-world/Cargo.toml --target wasm32-wasip2 --release',
        deps = [
            'examples/hello-world/src',
            'framework/runtime.wit',
        ],
        labels = ['execution-host'],
    )

    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' --build-context wasm=target/wasm32-wasip2/release' +
            ' -f components/execution-host/Dockerfile' +
            ' -t $EXPECTED_REF' +
            ' .'
        ),
        deps = [
            'components/execution-host/src',
            'components/execution-host/Cargo.toml',
            'target/wasm32-wasip2/release/hello_world.wasm',
        ]
    )

    helm_resource(
        'execution-host',
        chart = 'components/execution-host/helm',
        namespace=namespace,
        image_deps = [IMAGE_REF],
        image_keys = [('image.repository', 'image.tag')],
        labels = ['execution-host'],
        port_forwards=['3001:3000'],
        resource_deps=resource_deps,
    )

    local_resource(
        'eh: unit-tests',
        cmd = 'cargo test -p execution-host',
        deps = ['components/execution-host/src'],
        auto_init=False,
        trigger_mode = TRIGGER_MODE_MANUAL,
        labels = ['execution-host'],
    )

    local_resource(
        'eh: int-tests',
        cmd = 'nats pub fn.hello \'{"method": "GET", "path": "/hello", "body": "world"}\' --server nats://localhost:4222',
        resource_deps = ['execution-host'],
        auto_init=False,
        trigger_mode = TRIGGER_MODE_MANUAL,
        labels = ['execution-host'],
    )
