load('ext://helm_resource', 'helm_resource')

IMAGE_REF = 'wasm-platform-registry.localhost:5001/execution-host'

def execution_host(namespace, resource_deps=[]):
    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' --build-context workspace=.' +
            ' --build-arg WORKSPACE_DEPS_IMAGE=$TILT_IMAGE_0' +
            ' -f components/execution-host/Dockerfile' +
            ' -t $EXPECTED_REF' +
            ' components/execution-host'
        ),
        deps = [
            'components/execution-host/src',
            'components/execution-host/Cargo.toml',
            'proto/configsync/v1/configsync.proto',
            'framework/runtime.wit',
        ],
        image_deps = ['workspace-deps'],
    )

    helm_resource(
        'execution-host',
        chart = 'components/execution-host/helm',
        namespace=namespace,
        image_deps = [IMAGE_REF],
        image_keys = [('image.repository', 'image.tag')],
        labels = ['platform'],
        port_forwards=['3001:3000'],
        resource_deps=resource_deps,
    )
