load('ext://helm_resource', 'helm_resource')
load('../../tilt/namespace.Tiltfile', 'k8s_namespace')

def db_operator(namespace):
    k8s_namespace(namespace)
    helm_resource(
        'db-operator',
        namespace=namespace,
        chart='oci://docker.io/benwright/db-operator-chart:v1.0.10',
        labels=['platform'],
        flags=[
            '--set=image.repository=docker.io/benwright/db-operator',
            '--set=image.tag=v1.0.10',
        ],
    )
    local_resource(
        'db-operator-crds-ready',
        cmd='kubectl rollout status deployment/db-operator -n {} --timeout=120s'.format(namespace),
        resource_deps=['db-operator'],
        labels=['internal'],
    )

def wp_databases(namespace):
    helm_resource(
        'wp-databases',
        chart='components/wp-databases',
        namespace=namespace,
        labels=['platform'],
        deps=['components/wp-databases'],
        resource_deps=[
            'db-operator-crds-ready',
        ],
    )
