IMAGE_REF = 'wasm-platform-registry.localhost:5001/module-cache'

def module_cache():
    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' --build-context workspace=.' +
            ' --build-arg WORKSPACE_DEPS_IMAGE=$TILT_IMAGE_0' +
            ' -f components/module-cache/Dockerfile' +
            ' -t $EXPECTED_REF' +
            ' components/module-cache'
        ),
        deps = [
            'components/module-cache/src',
            'components/module-cache/Cargo.toml',
        ],
        image_deps = ['workspace-deps'],
    )

    k8s_resource(
        'module-cache',
        labels = ['platform'],
    )
