load('ext://helm_resource', 'helm_resource')

IMAGE_REF = 'wasm-platform-registry.localhost:5001/module-cache'

def module_cache(namespace):
    custom_build(
        IMAGE_REF,
        command = (
            'docker build' +
            ' --build-context workspace=.' +
            ' --build-arg WORKSPACE_DEPS_IMAGE=$TILT_IMAGE_0' +
            ' -f components/module-cache/Dockerfile' +
            ' -t $EXPECTED_REF' +
            ' components/module-cache'
        ),
        deps = [
            'components/module-cache/src',
            'components/module-cache/Cargo.toml',
        ],
        image_deps = ['workspace-deps'],
    )

    helm_resource(
        'module-cache',
        chart = 'components/module-cache/helm',
        image_deps = [IMAGE_REF],
        image_keys = [('image.repository', 'image.tag')],
        labels = ['platform'],
        namespace=namespace,
    )
