apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: NatsCluster
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.databases.labels" . | nindent 4 }}
spec:
  natsVersion: {{ .Values.databases.nats.version | quote }}
  jetStream:
    storageSize: {{ .Values.databases.nats.jetStream.storageSize }}
---
apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: NatsAccount
metadata:
  name: {{ .Release.Name }}-nats-wp-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.databases.labels" . | nindent 4 }}
spec:
  clusterRef: {{ .Release.Name }}-nats
  users:
    - username: {{ .Values.databases.nats.wpOperator.username }}
      secretName: {{ .Values.databases.nats.wpOperator.secretName }}
      permissions:
        publish:
          allow:
            - ">"
        subscribe:
          allow:
            - ">"
---
apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: NatsAccount
metadata:
  name: {{ .Release.Name }}-nats-execution-host
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.databases.labels" . | nindent 4 }}
spec:
  clusterRef: {{ .Release.Name }}-nats
  users:
    - username: {{ .Values.databases.nats.executionHost.username }}
      secretName: {{ .Values.databases.nats.executionHost.secretName }}
      permissions:
        publish:
          allow:
            - ">"
        subscribe:
          allow:
            - ">"
  exports:
    - subject: "http.>"
      type: service
    - subject: "fn.>"
      type: service
---
apiVersion: db-operator.benjamin-wright.github.com/v1alpha1
kind: NatsAccount
metadata:
  name: {{ .Release.Name }}-nats-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wasm-platform.databases.labels" . | nindent 4 }}
spec:
  clusterRef: {{ .Release.Name }}-nats
  users:
    - username: {{ .Values.databases.nats.gateway.username }}
      secretName: {{ .Values.databases.nats.gateway.secretName }}
      permissions:
        publish:
          allow:
            - ">"
        subscribe:
          allow:
            - ">"
  imports:
    - account: {{ .Release.Name }}-nats-execution-host
      subject: "http.>"
      type: service
