apiVersion: wasm-platform.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: examples
spec:
  module: hello-world
  keyValue: hello-world
  http:
    path: /hello
    methods:
      - GET
