apiVersion: wasm-platform.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: examples
spec:
  keyValue: hello-world
  functions:
    - name: handler
      module: hello-world
      trigger:
        http:
          path: /hello
          methods:
            - GET
